type Address {
  id: ID!
  name: String
}

type Attachment {
  id: ID!
  filename: String
  contentType: String
  contentDisposition: String
  checksum: String
  size: Int
  content: String
  contentId: String
  cid: String
  related: Boolean
}

type HeaderLine {
  id: ID!
  line: String
}

type Mail {
  id: ID!
  subject: String
  from: [Address!]!
  to: [Address!]!
  cc: [Address]
  bcc: [Address]
  date: Date!
  messageId: String!
  inReplyTo: String
  replyTo: Address
  references: [String]
  html: Boolean
  text: String
  textAsHtml: String
  attachments: [Attachment]
  headerLines: [HeaderLine!]!
}

type Query {
  parse(id: ID, rawEmail: String!): Mail!
}
