type Address {
  id: ID!
  name: String
  address: String
  group: [String]
}

type Attachment {
  id: ID!
  filename: String
  contentType: String
  contentDisposition: String
  checksum: String
  size: Int
  content: String
  contentId: String
  cid: String
  related: Boolean
}

type HeaderLine {
  id: ID!
  key: String
  line: String
}

type Mail {
  id: ID!
  subject: String
  from: [Address]
  to: [Address]
  cc: [Address]
  bcc: [Address]
  date: Date
  messageId: String
  inReplyTo: String
  replyTo: Address
  references: [String]
  html: String
  text: String
  textAsHtml: String
  attachments: [Attachment]
  headerLines: [HeaderLine]
}

type Query {
  parse(rawEmail: String!): Mail
}
